CREATE DATABASE ACE079BCT051

CREATE TABLE 
STUDENT
(
    ID INT,
    STU_NAME VARCHAR(25),
    RN INT,
    BATCH VARCHAR(10)
)
SELECT * FROM STUDENT;

INSERT INTO STUDENT
VALUES
(51,'RUSHA MANANDHAR',048,'BCT079'),
(48,'ROHAN SHRESTHA',045,'BCT079'),
(21,'abcd',284,'duwd');
SELECT *FROM STUDENT;

CREATE TABLE 
TEACHER
(
    TID INT,
    T_NAME VARCHAR(25),
    FACULTY VARCHAR(20)
)
SELECT *FROM TEACHER;
INSERT INTO TEACHER
VALUES
(51,'RUSHA MANANDHAR','C'),
(48,'ROHAN SHRESTHA','E'),
(21,'abcd','D');
SELECT TID,FACULTY FROM TEACHER;
SELECT ID,STU_NAME FROM STUDENT;

DROP TABLE STUDENT;
TRUNCATE TABLE TEACHER;
TRUNCATE TABLE TEACHER;

INSERT INTO STUDENT(ID,STU_NAME)
VALUES
(
23,'HELPP'
);
SELECT *FROM STUDENT;

INSERT INTO STUDENT
(ID,STU_NAME,BATCH)
VALUES
(23,'HELPP','BCT')
SELECT * FROM STUDENT

INSERT INTO STUDENT
(BATCH,STU_NAME,ID)
VALUES
('BCT','HELPP',23)
SELECT * FROM STUDENT

ALTER TABLE STUDENT
ALTER COLUMN BATCH VARCHAR(29)

ALTER TABLE TEACHER 
ADD SALARY INT

CREATE TABLE 
STU_ABC
(
    ID INT,
    STUD_NAME VARCHAR(25)
)
INSERT INTO STU_ABC
SELECT ID,STUD_NAME FROM STUDENT

CREATE TABLE STUDENT_BCD AS
SELECT ID,STU_NAME
FROM STUDENT;